### ISSUE TITLE
curlio does not work with host header

### ISSUE THREAD

**Issue by GoCoder7** [Kei-K23/curlio#2]
Hi
thank you for this useful tool for web testing
with this, i could send thousands request to the server at once with terminal.
i'm following tutorial about actix-web
and in hosting guard, I ran into the panic of the curlio.
here is the [link](https://actix.rs/docs/application#application-guards-and-virtual-hosting) for that tutorial,
and this is what i have encountered
```shell
curlio -H "Host: www.rust-lang.org" http://127.0.0.1:8080 
thread 'main' panicked at /Users/gohyeoncheol/.cargo/registry/src/index.crates.io-6f17d22bba15001f/curlio-0.4.3/src/main.rs:181:60:
called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    9640 abort      curlio -H "Host: www.rust-lang.org" http://127.0.0.1:8080
```
thanks a lot

**Comment by Kei-K23** [comment]
Hello @GoCoder7, Thank for your feedback and testing curlio. I tested out following your case and the only case that occur the error is wrong definition of -H format. Below is the correct usage of -H (custom headers definition).

`curlio "http://127.0.0.1:8080/" -H '{"Host" : "www.rust-lang.org"}'`

I use JSON format to defined -H values.

Below is my testing for your case.

`// main.rs
use actix_web::{guard, web, App, HttpResponse, HttpServer};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .service(
                web::scope("/")
                    .guard(guard::Host("www.rust-lang.org"))
                    .route(
                        "",
                        web::to(|| async { HttpResponse::Ok().body("This is rust lang") }),
                    ),
            )
            .service(
                web::scope("/")
                    .guard(guard::Host("users.rust-lang.org"))
                    .route(
                        "",
                        web::to(|| async { HttpResponse::Ok().body("This is users rust lang") }),
                    ),
            )
            .route("/", web::to(HttpResponse::Ok))
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
`

Output for above code

`curlio "http://127.0.0.1:8080/" -H '{"Host" : "www.rust-lang.org"}'  
This is rust lang

curlio "http://127.0.0.1:8080/" -H '{"Host" : "users.rust-lang.org"}'
This is users rust lang
`

If you have any questions about curlio. Feel free to ask.

**Comment by GoCoder7** [comment]
oh i think i didn't read the help properly..
thanks a lot!
